name: Patch Alpha

on:
  pull_request:
    types: [closed]
    branches: [alpha]

env:
  GODOT_VERSION: 4.5
  EXPORT_NAME: example
  PROJECT_PATH: . # NOTE: If your `project.godot` is at the repository root, set `PROJECT_PATH` to ".".s

jobs:
  build:
    name: Build Godot Project
    uses: ./.github/workflows/build.yml
    if: startsWith(github.head_ref, 'patch')
  create-release:
    name: Create new alpha release
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'patch')
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Create Tag From Feature
        id: release_tag
        uses: mistermaxis/update-tag-action@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          prefix: v
          bump: patch
          suffix: alpha
          replace_suffix: false
      - name: Download Files
        uses: actions/download-artifact@v4
        with:
          path: build
          merge-multiple: true
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/*
          tag: ${{ steps.release_tag.outputs.updated_tag }}
          name: Release ${{ steps.release_tag.outputs.updated_tag }}
          makeLatest: true
