name: prerelease-alpha
on:
  pull_request:
    types: [closed]
    branches: [alpha-feat/*]

env:
  GODOT_VERSION: 4.5
  EXPORT_NAME: example
  PROJECT_PATH: . # NOTE: If your `project.godot` is at the repository root, set `PROJECT_PATH` to ".".

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Create Release Tag
        uses: mistermaxis/update-tag-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          prefix: v
          bump: prerelease
          suffix: alpha
  build:
    runs-on: ubuntu-latest
    needs: tag
    steps:
      - name: Build Godot
        uses: ./.github/workflows/build.yml
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.EXPORT_NAME }}-${{ matrix.target-platform.build_dir }}
          path: build/${{ matrix.target-platform.build_dir }}/${{ env.EXPORT_NAME }}-${{ matrix.target-platform.build_dir }}-${{ needs.tag.outputs.updated_tag }}.${{ matrix.target-platform.extension }}
  create-release:
    name: Create new alpha prerelease version
    runs-on: ubuntu-latest
    needs: [build, tag]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Download Files
        uses: actions/download-artifact@v4
        with:
          path: build
          merge-multiple: true
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/*
          tag: ${{ needs.tag.outputs.updated_tag }}
          name: Release ${{ needs.tag.outputs.updated_tag }}
          prerelease: true
